import subprocess
import math

#generate the sequence file - done
#generate all the init config/top files - done

# generate all pairs of interest - done

# no need for mutual traps - done

# generate a new input file for each bc each actually needs one, make sure we are not printing energy

# do MD browninan motion sim

# for like 10^6 time steps?

# call oxDNA

# parse the output results with parse_pairs


DNA_lengths_of_interest = [500, 1000, 2000, 5000] #, 10000, 20000, 50000]
concentrations_of_interest = [.1, 1, 10, 100, 1000]

basic_top_seq = ""

generate_sticky_sequences_file = "generate_sticky_seq.py"

generate_pairs_of_interest_file = "generate_pairs_of_interest_data.py"

parse_hydrogen_bonds_file = "parse_pairs_of_interest_output.py"

oxDNA_executable_file_path = "/groups/KaihangWang_Group/jzhou2/cuda_oxDNA/oxDNA/build/bin/oxDNA"

self_directory = "/groups/KaihangWang_Group/jzhou2/cuda_oxDNA/oxDNA/examples/real_world_gpu/"

# 500, 1000, 2000, 5000
top_sequences = [["TTTTGATGTGATGTACCCCGCGTCACCCCCTTTAGCAGCCGAGCAATGGAGTACAGTATTGGGCACACATAGCAAGACTATTATGCCGCGGCGTGCCGCGTTCTGGTTCGTCAATAAGCACATGAGATGAACTAGCGGTTGTGTACTAGTCTCGATGTCCCCCAGCCGTAACAGTTAACCTCCTAACGTCATCTCCGCCTACGTGTTGTCAAGCCGGTACCATAGTGAAGGAACGATGCCGGTGCTGCGAAAAGAGTCCGGATATCTTTGTCGCAGCTAGCCCCGGTTAGATAGGTGGACTTACGGCAGTATACGGGGCCATTAAGAGGCCTCTGACTCTCTGCCCGTTAGCTTAGTTATGAGGCACGGATGGACTTCTAGTCAGTTTCTCAAACGTCGGGCGTGAGACATTCCCTCAGCTTTTATACGGGGAGATGACTCTTACAATGTGTTCGTTTACCCCAAAGGGTCCCGGGTATTACCTAGAACACACCTGACGT"],
["TTTTGATGTGATGTACCCCGCGTCACCCCCTTTAGCAGCCGAGCAATGGAGTACAGTATTGGGCACACATAGCAAGACTATTATGCCGCGGCGTGCCGCGTTCTGGTTCGTCAATAAGCACATGAGATGAACTAGCGGTTGTGTACTAGTCTCGATGTCCCCCAGCCGTAACAGTTAACCTCCTAACGTCATCTCCGCCTACGTGTTGTCAAGCCGGTACCATAGTGAAGGAACGATGCCGGTGCTGCGAAAAGAGTCCGGATATCTTTGTCGCAGCTAGCCCCGGTTAGATAGGTGGACTTACGGCAGTATACGGGGCCATTAAGAGGCCTCTGACTCTCTGCCCGTTAGCTTAGTTATGAGGCACGGATGGACTTCTAGTCAGTTTCTCAAACGTCGGGCGTGAGACATTCCCTCAGCTTTTATACGGGGAGATGACTCTTACAATGTGTTCGTTTACCCCAAAGGGTCCCGGGTATTACCTAGAACACACCTGACGTGGTATCGGTCCTTCATCACTATGCGCTACCTTGATAGGTGTGGCCTCGACTTGACACCTCACTTAAAGATTTTGACGAGCAGTTCCTCTAGAATGTTCGTCAGCACGCTAAGCGCCAGTACAGAGGTGGTGGTGCCGTTCTCGTGGGAGAAGAACTTATTATGGGTGTACGACTGTCGACTTCATGATAACTGTGATCAACTGGTTCAAAGCCTAGTGTGAGAGTAGGAACGAAAGGAGAGCTTCCGATGCTCAGGGGCTATCGCGACAGAGAATCCCCCCCTGGCCTGTTAGGGTCGGTATTAAGTTAGTGTCTTATCGCTGCCGGGGACAAGTCCTACAGCTGTAGGAGATGTAATTGCGTGGAGCCCCTAAGCATAGTGTTATGAAGATGATTGGGTCGTGGACGAACTACGGGTAAGTCGACCGAATCTATCTGTGCGCGATGTCCAAGGGATCAACCGGGGTTTATACGCGGCGCACATTAGTTAACTGGTCTCA"],
["TTTTGATGTGATGTACCCCGCGTCACCCCCTTTAGCAGCCGAGCAATGGAGTACAGTATTGGGCACACATAGCAAGACTATTATGCCGCGGCGTGCCGCGTTCTGGTTCGTCAATAAGCACATGAGATGAACTAGCGGTTGTGTACTAGTCTCGATGTCCCCCAGCCGTAACAGTTAACCTCCTAACGTCATCTCCGCCTACGTGTTGTCAAGCCGGTACCATAGTGAAGGAACGATGCCGGTGCTGCGAAAAGAGTCCGGATATCTTTGTCGCAGCTAGCCCCGGTTAGATAGGTGGACTTACGGCAGTATACGGGGCCATTAAGAGGCCTCTGACTCTCTGCCCGTTAGCTTAGTTATGAGGCACGGATGGACTTCTAGTCAGTTTCTCAAACGTCGGGCGTGAGACATTCCCTCAGCTTTTATACGGGGAGATGACTCTTACAATGTGTTCGTTTACCCCAAAGGGTCCCGGGTATTACCTAGAACACACCTGACGTGGTATCGGTCCTTCATCACTATGCGCTACCTTGATAGGTGTGGCCTCGACTTGACACCTCACTTAAAGATTTTGACGAGCAGTTCCTCTAGAATGTTCGTCAGCACGCTAAGCGCCAGTACAGAGGTGGTGGTGCCGTTCTCGTGGGAGAAGAACTTATTATGGGTGTACGACTGTCGACTTCATGATAACTGTGATCAACTGGTTCAAAGCCTAGTGTGAGAGTAGGAACGAAAGGAGAGCTTCCGATGCTCAGGGGCTATCGCGACAGAGAATCCCCCCCTGGCCTGTTAGGGTCGGTATTAAGTTAGTGTCTTATCGCTGCCGGGGACAAGTCCTACAGCTGTAGGAGATGTAATTGCGTGGAGCCCCTAAGCATAGTGTTATGAAGATGATTGGGTCGTGGACGAACTACGGGTAAGTCGACCGAATCTATCTGTGCGCGATGTCCAAGGGATCAACCGGGGTTTATACGCGGCGCACATTAGTTAACTGGTCTCAACATCAGTATTTGAGCACCGGTTTATCTCGCCCGGACGTCTGATAGCCGCGTTGGATTAATGGGTCAGTTGAAGAAGCTGCTGACTTTTTGACTTCATGTTACAGTCTGCAACGCCCGTTGGCCGTATTAGAGACGCGTTGGATTAGCCAACCCGCCGTGGATCAGGCACGGCGCCCTTGTAGTACCGAGAAAAGCTTGTCAAGCCGAAGCCAGCTACAATGCTATTGCGGCTAAAAACGCCGAAGCATGGCCACACGGCAGGATAATTACGCCTAGCAACCACCGTAGCTATAAATCCTCGTGCCCGAGGCCAACGGTGGCGGCTGACGGCCGGGGATTTCGTTAATACCGAACATGGCTTTGTAAGAGTATATAGTCTCGGCGAAGCGGTGCTCTTGGCGGTTAAGTGCACAGCTATTTAAGCAGAATAGCCCATTTAGTCGGATTCCTCATTTCTTTCCCAGGCATTATGAGGCCTCGGCTTTGCGGTCCTGCACGCGGAGCCAGTACGCCACTTCACGTCAATCCAGAAATACGGATGTGAGAATTTGCTCATGCCACTGCGTCTAAATATCAGGATAGCCCCAAACTGGGGGACGCCTCCGCCGAGATGAGTCAGCTTCGGTCATAAAGTAGATGTCGGCGTTAGTTTGTGCGCAGTGCACACGGACCGTGGTGTCCTTGTTTACTTATGTCCGTAGGCGGGGTCGCACAGGCTCTAGTAGAGTCTTCTCCGAGGATGTTGCGGCTTAATTCTTGGCCACAGGGCCGGCGAGATAGTTCTGAGCAGAAGTGATCACACTGAATACCTAGGCCAAACGCGCCTGGGTACCGGTCCCAGAGTTCTCCTTGCACTCGCTAGCAGCTCCTCTCTAGGCAACAATCTACGTCATTTGCACCAGTTTTCGATCCTTGGTGTAGATATGGGAACTCTGATATACTTGTACTGTCCTTACGGAGCAGGGGTGCATCAGACAGCCTAAGGTGGACCGGCGATAT"],
["TTTTGATGTGATGTACCCCGCGTCACCCCCTTTAGCAGCCGAGCAATGGAGTACAGTATTGGGCACACATAGCAAGACTATTATGCCGCGGCGTGCCGCGTTCTGGTTCGTCAATAAGCACATGAGATGAACTAGCGGTTGTGTACTAGTCTCGATGTCCCCCAGCCGTAACAGTTAACCTCCTAACGTCATCTCCGCCTACGTGTTGTCAAGCCGGTACCATAGTGAAGGAACGATGCCGGTGCTGCGAAAAGAGTCCGGATATCTTTGTCGCAGCTAGCCCCGGTTAGATAGGTGGACTTACGGCAGTATACGGGGCCATTAAGAGGCCTCTGACTCTCTGCCCGTTAGCTTAGTTATGAGGCACGGATGGACTTCTAGTCAGTTTCTCAAACGTCGGGCGTGAGACATTCCCTCAGCTTTTATACGGGGAGATGACTCTTACAATGTGTTCGTTTACCCCAAAGGGTCCCGGGTATTACCTAGAACACACCTGACGTGGTATCGGTCCTTCATCACTATGCGCTACCTTGATAGGTGTGGCCTCGACTTGACACCTCACTTAAAGATTTTGACGAGCAGTTCCTCTAGAATGTTCGTCAGCACGCTAAGCGCCAGTACAGAGGTGGTGGTGCCGTTCTCGTGGGAGAAGAACTTATTATGGGTGTACGACTGTCGACTTCATGATAACTGTGATCAACTGGTTCAAAGCCTAGTGTGAGAGTAGGAACGAAAGGAGAGCTTCCGATGCTCAGGGGCTATCGCGACAGAGAATCCCCCCCTGGCCTGTTAGGGTCGGTATTAAGTTAGTGTCTTATCGCTGCCGGGGACAAGTCCTACAGCTGTAGGAGATGTAATTGCGTGGAGCCCCTAAGCATAGTGTTATGAAGATGATTGGGTCGTGGACGAACTACGGGTAAGTCGACCGAATCTATCTGTGCGCGATGTCCAAGGGATCAACCGGGGTTTATACGCGGCGCACATTAGTTAACTGGTCTCAACATCAGTATTTGAGCACCGGTTTATCTCGCCCGGACGTCTGATAGCCGCGTTGGATTAATGGGTCAGTTGAAGAAGCTGCTGACTTTTTGACTTCATGTTACAGTCTGCAACGCCCGTTGGCCGTATTAGAGACGCGTTGGATTAGCCAACCCGCCGTGGATCAGGCACGGCGCCCTTGTAGTACCGAGAAAAGCTTGTCAAGCCGAAGCCAGCTACAATGCTATTGCGGCTAAAAACGCCGAAGCATGGCCACACGGCAGGATAATTACGCCTAGCAACCACCGTAGCTATAAATCCTCGTGCCCGAGGCCAACGGTGGCGGCTGACGGCCGGGGATTTCGTTAATACCGAACATGGCTTTGTAAGAGTATATAGTCTCGGCGAAGCGGTGCTCTTGGCGGTTAAGTGCACAGCTATTTAAGCAGAATAGCCCATTTAGTCGGATTCCTCATTTCTTTCCCAGGCATTATGAGGCCTCGGCTTTGCGGTCCTGCACGCGGAGCCAGTACGCCACTTCACGTCAATCCAGAAATACGGATGTGAGAATTTGCTCATGCCACTGCGTCTAAATATCAGGATAGCCCCAAACTGGGGGACGCCTCCGCCGAGATGAGTCAGCTTCGGTCATAAAGTAGATGTCGGCGTTAGTTTGTGCGCAGTGCACACGGACCGTGGTGTCCTTGTTTACTTATGTCCGTAGGCGGGGTCGCACAGGCTCTAGTAGAGTCTTCTCCGAGGATGTTGCGGCTTAATTCTTGGCCACAGGGCCGGCGAGATAGTTCTGAGCAGAAGTGATCACACTGAATACCTAGGCCAAACGCGCCTGGGTACCGGTCCCAGAGTTCTCCTTGCACTCGCTAGCAGCTCCTCTCTAGGCAACAATCTACGTCATTTGCACCAGTTTTCGATCCTTGGTGTAGATATGGGAACTCTGATATACTTGTACTGTCCTTACGGAGCAGGGGTGCATCAGACAGCCTAAGGTGGACCGGCGATATAGACCACCAGCCCACAGCTTACAAAACGACCTCACCGCACGGGGCCTTGGCCCTAGGGAGCTTCACCGGCGATCACTCTGTCCCAGTAGCTCCTACCCAATAGTCTTATGGCTTTCCACGGGGGCGGAGTCAGAGCACTAAACGCAGGCAGGCCACCAGACCAGCTAACCGACATCGGTGCATATCGCTGGTAGAACATCAGATAACTTCCGGGCAAAGTCATGATCTCAATGCCAGATTGAAGGCTATAGAAATCATCTAAGCAATAAACTACGTATGCCGGAGAAGCACTCGATGCGTAACCTGTGGGGATACCTGACGAACCCCGTCTAGATCAGAAATGAATTATCTTGTAAACTCGTTCTAAACACCAGGAGTACATTACGTAGGATTAAATGAAGCAATGCTTCTCCAAGTTCAATAAGGAGGAAAGACGATCTGCGTCCAACGAGGTCGGGATGGAGCTTAAAGACGCGATTAGGTGGAATCTAGTTGGGCAAAAGGTGACTCGGACCGTGGCGTCTAATGAGCTACGTAGAAATGGCGCGGCCAGGTCGGGTCTTCAGAATCGCGTACCAAACCTCTTGTTCAGGCGCTCCTCTACCTAGTTAAAGTCCATCGGAGTGCGAGAGCCATGTCAACATGGAGAGCCGAGTAATCTAGTGTGTCTATTGACCGACCATTTAAGTGCTTGTAGTCAACGCAGTATTGTGCACTCATAACCATCGCACGTTTAATGTTAACTGCGTTCATGCGTAGGACTTCGCGCGTCCCGGGGAGCATCTCTCCCAACCGACTAGAGGTATGCAGGACCACGCCCACGAAAAGTAGTTGAGTGTAGCATGACCATGTCCCGCGTGCGGACTTTAACAAGGTTGTACGAGCAGACCGTGTGGTGTCTAGTAATTCGTATGCGCTGACATAAAGACTTCTTTAGGAGGTACATAATGATATAGGATTACGTTACGTAGATTTACGAAACCGGCGCGCTCGACCGTTCCCTGAGGTACAAGCACTAACCAAGTCGCAACGAAGAGGCCCCGGCGTCTACGAGTCACAGGTCACAACAATATCCCCCCGGGAATGGCGGGAGACAGGTATGAGAGTTGACTAAACATGCGCACATTGTTTTACACCTTACCTGGATGTCCGGATCACTTATCGACAACGTTACCAACGACCACCATCGACAGATTACGTGATTCTTTGTCCAGGACGAGCTCCACCGAACCAGTGGGCGCTCTATCCATTTCCTGATGGTGCCCTAAAAAACGCGATCTAACATGCTCACTCCAGATGGCACATTAGACTACCATGCAAGGCACCCTACCCAAGTCACATCTTAATAACCATAGATCCGAGGGTGGCCCTTGTTTTTTAAGACTTATCGCGCGCCAGACCTTTGCCAGCAGAAGGTGCCCCCGAATAGAGCAGCGCCGAGATAGCTCGACTACTATACAGCTAGACGCAGGCTACAGCGTCGGTACATCCTTATCTCCCCGAACTACCTTAGCCAAAATGCGGGGTATTCGATTATAAAGGATTCAGCTCAGTTATTCCTTCCCACCCATCCTAGGGTACATTGATACACCCCATAGCAGCCTAAGACACTTTTTCCTATCTTGACGCGGGCCAGATTTTCGGTTTTTAAGACTCTGTACACGCACTTAGGGGGCCTCAGGTCCTGACCCGCCGGTACGGATTGCTACTGCGCCGGGCCCGGCTCATCTTCAACATGGCGTTACATTATAAATTTAAAGCAAGAAAGCGTAAAGTTAAGGCTATCTATCATCGGTCAGGCTACATGCATATTACCTGACACGTGCATGGATATGGAGTGCGATCATAATACGTTAAATTCCGGGTAGAAATTGTCTCCACAGCTATTCTATGTACGCGCTATGTTCCTTGCGCTGTGACCCGATTGCGAAGCCTGACGGTGAACTACCCGTGGTACAAAAGACCTTGAAGGTAAATTGATCCGTGGGCTAAAGTGCATAGATGATTTGCGTCCCTCGCTACCGGAAGTGAATTGCCAGTATGTACTACCGACAACTTTACTAGTAATAGCACGTGTTCTCTTATTTACCAGGCCAACGGCGGGTCCGAGGAATGACTATTGATCAGTGCATCGAGCTCATGCTATGTGCATTATCAGCCGATGCGCAATCCAGTTTGTAGGACCACACTTAGTGCGCACTACTACGACACGTGATCCGTGCCTGCGGCCACCGAATGTCTATTGCCCCCACAGCTTTTCGTTACCGCGCGTAGGAGTAGCGGCCACTTGACCAACCAGTCCCAGTTCCACTACGTAGAACGGTCCGCCTTCGTACTGCTTTCGTCGTCATGTGGCACCTTCGACTGAAATATCAAAAGTGCTCACAAAGTGGGACCAGCACTTCCGGTGGTGTAGTAACCTCTGTTTACGAGTTTGTGCTGGAGTAGATAAGAGCACCGATAACTCCCTCCTAAGTTAAGTCACTACGCTGGGTGGACGGGTAGAATAAATACTAATAGCAATCTGCAGCCCACTTAGTATCGGTCGAGAAGTCCATGTGCCAAAGTCTGGTTGGAACAGGACTGAGTTCTTACGGGTAGTTTTAATGCTTCGCCAAACAAAAATACAGACAGATATTTGTAGATGCACGATACTTAGTTTACAGTGCGCAAGACTAAACCCGATTTCCCTGTACCGAGCAGCTAGATGACAGTGTCGCAGCATAGGGTTAACCTCCGTGCGGACACTTCTAACAATTTCCCGCTAAGAAATTTGGGCCTTAGCTTTTCGTTCTGATTACGGACTGTCATAGAGGGTTCCCCGTAACGTAGTAGTGTCCTGGGTTCCTGCACGCTCCGTCAACTTTTGAATGTTATTGATCACCTACAGAATTCTTACTAGTTTGGTCCAGAGATCGCTTCGCCTTCGCCGTAGAATCACCTGTCCTAAGGTCATGAGCTGAACCTCGGTAAGGTCTTGGAAAATTTATTGTGCTACCG"]]

bot_seq = "AAAA"

len_sticky = str(len(bot_seq))

# 500, 1000, 2000, 5000
adjusted_tail_counts = [[9.986078024277075, 9.904804390913862, 9.745334565892431, 9.295713057315137], 
[9.986078024277074, 9.90480439091386, 9.745334565892428, 9.295713057315135], 
[9.986078024277075, 9.904804390913862, 9.745334565892428, 9.295713057315135], 
[9.986078024277077, 9.90480439091386, 9.74533456589243, 9.295713057315133], 
[9.986078024277075, 9.904804390913862, 9.74533456589243, 9.295713057315135]] 
adjusted_vol = [[82644628099.17355, 163934426229.5082, 322580645161.29034, 769230769230.7693], 
[8264462809.917356, 16393442622.950819, 32258064516.129032, 76923076923.07692], 
[826446280.9917356, 1639344262.2950819, 3225806451.612903, 7692307692.307693], 
[82644628.09917356, 163934426.2295082, 322580645.16129035, 769230769.2307693], 
[8264462.809917355, 16393442.62295082, 32258064.51612903, 76923076.92307693]]

row_len = len(DNA_lengths_of_interest)
col_len = len(concentrations_of_interest)
for i in range(0, 1):
    for j in range(0, 1):
        position = f"{i}_{j}_"
        # # generating sticky_sequences.txt
        sticky_seq_file = position + "sticky_sequences.txt"

        num_molecules = str(adjusted_tail_counts[i][j])

        vol = adjusted_vol[i][j]
        box_side_len = str(math.cbrt(vol))

        top_seq = top_sequences[j][0]

        # bot sticky end is bot_seq defined outside this scope

        output_topo_file_name = position + "topo_file.txt"

        output_config_file_name = position + "init_config.txt"
        
        subprocess.run(["python" + " " + generate_sticky_sequences_file + " " + sticky_seq_file + " " + num_molecules + " " + box_side_len + " " + top_seq + " " + bot_seq + " " + output_topo_file_name + " " + output_config_file_name], shell=True)

        # generating pairs of interest

        tot_len = str(DNA_lengths_of_interest[j])

        len_of_strand_excluding_sticky = str(int(tot_len) - int(len_sticky))

        output_pairs_of_interest_file_name = position + "pairs_of_interest.txt"

        subprocess.run(["python" + " " + generate_pairs_of_interest_file + " " + len_sticky + " " + len_of_strand_excluding_sticky + " " + tot_len + " " + num_molecules + " " + output_pairs_of_interest_file_name], shell=True)

        # generation of new input file

        input_file_name = position + "input"

        input_file = open(input_file_name, "w")

        template_file = open("template_input", "r")

        for number, line in enumerate(template_file):
            if number == 0:
                line = f"output_prefix = " + position + "\n"
            if number == 1:
                line = f"topology = " + position + "topo_file.txt\n"
            if number == 2:
                line = f"conf_file = " + position + "init_config.txt\n"
            if number == 11:
                line = f"        order_parameters_file = " + position + "pairs_of_interest.txt\n"
            input_file.write(line)
        
        input_file.close()

        template_file.close()

        # running oxDNA (i.e. runnin the simulation)
        subprocess.run([oxDNA_executable_file_path + " " + self_directory + input_file_name], shell=True)

        # parsing hydrogen bond output

        input_h_file_name = position + "h_bonds.txt"

        run_output_file_name = position + "output_file.txt"     

        subprocess.run(["python" + " " + parse_hydrogen_bonds_file + " " + tot_len + " " + input_h_file_name + " " + run_output_file_name + " " + num_molecules + " " + box_side_len + " " + position], shell=True)
